server_connect_timeout: 10000
listeners:
  - query_port: 25565
    tab_list: GLOBAL
    query_enabled: false
    proxy_protocol: false
    ping_passthrough: false
    priorities:
      - main
    bind_local_address: true
    host: "0.0.0.0:25577"
    max_players: 125
    tab_size: 60
    force_default_server: false
    motd: '§2Building with more than just blocks.§r'
    forced_hosts:
      ${CIV_PVP_HOSTNAME}: pvp
      ${CIV_HOSTNAME}: main
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: ${CIV_TIMEOUT_TIME}
player_limit: -1
ip_forward: true
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: b074eed2-e7a2-4cda-bc1c-badda2fb5223
online_mode: true
forge_support: true
disabled_commands:
servers:
  main:
    motd: '§2Building with more than just blocks.§r'
    address: "paper:25565"
    restricted: false
  pvp:
    motd: "§2Building with more than just blocks.§r\n§4§lPvP server§r"
    address: "pvp:25565"
    restricted: false
