# Publish and release a project when a tag is created.
# TODO: Currently, this only supports plugins.
name: ğŸ·ï¸ Tag Pushed

on:
  push:
    tags:
      - '*-v*.*.*'

jobs:
  split_values:
    name: Split Values
    runs-on: ubuntu-latest

    outputs:
      project: ${{ steps.split.outputs.project }}

    steps:
      - name: Split Project Name
        id: split
        env:
          TAG: ${{ github.ref_name }}
        run: echo "project=$(cut -d '-' -f 1 <<< $TAG)" >> $GITHUB_OUTPUT

  call_publish_gradle:
    needs: split_values
    name: â˜ï¸ Call Publish Gradle
    uses: ./.github/workflows/publish_gradle_project.yaml
    secrets: inherit
    with:
      category: plugins
      project: ${{ needs.split_values.outputs.project }}

  call_release_gradle:
    needs: split_values
    name: â˜ï¸ Call Release Gradle
    uses: ./.github/workflows/release_gradle_project.yaml
    secrets: inherit
    with:
      category: plugins
      project: ${{ needs.split_values.outputs.project }}
